"""1

Revision ID: 995da16ed39a
Revises: e212b86270ab
Create Date: 2026-07-03 10:41:39.672430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '995da16ed39a'
down_revision: Union[str, Sequence[str], None] = 'e212b86270ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'project',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_column('reports', 'planned_work_time')
    op.drop_column('reports', 'tomorrow_plan')
    op.drop_column('reports', 'start_time')
    op.drop_column('reports', 'work_summary')
    op.drop_column('reports', 'difficulty')
    op.drop_column('reports', 'proposal')
    op.drop_column('reports', 'work_detail')
    op.drop_column('reports', 'actual_hours')
    op.drop_column('reports', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('actual_hours', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('work_detail', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('proposal', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('difficulty', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('work_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('tomorrow_plan', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('planned_work_time', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('reports', 'project',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    # ### end Alembic commands ###
